backend:
  name: git-gateway
  branch: master

media_folder: "uploads/" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "person" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Person" # Used in the UI, ie.: "New Post"
    folder: "src/people" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name", name: "title", widget: "string", tagname: "h1"}
      - {label: "Job-Title", name: "jobTitle", widget: "string", tagname: "h2"}
      - {label: "Image", name: "image", widget: "image", tagname: "img"}