backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - label: "General Content"
    name: "generalContent"
    create: false
    delete: false
    files:
      - label: "Header"
        name: "siteHeader"
        file: "_data/header.yml"
        fields:
          - {label: "Background", name: "background", widget: "image"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Popout Tagline", name: "popoutTagline", widget: "string"}
          - {label: "Popout Text Block", name: "popoutTextBlock", widget: "markdown"}
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - {label: "Character Image", name: "characterImage", widget: "image"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Text Block", name: "textBlock", widget: "markdown"}
      - label: "What We Do"
        name: "whatWeDo"
        file: "_data/what-we-do.yml"
        fields:
          - {label: "Image", name: "characterImage", widget: "image"}
          - {label: "Tagline", name: whatWeDoTagline, widget: string}
          - {label: "Text Block", name: whatWeDoTextBlock, widget: markdown}
      - label: "Get In Touch"
        name: "getInTouch"
        file: "_data/get-in-touch.yml"
        fields:
          - {label: "Get In Touch Image", name: "image", widget: "image"}
          - {label: "Tagline", name: "tagline", widget: string}
          - {label: "Button Text", name: "buttonText", widget: string}
          - {label: "Success Message", name: "buttonText", widget: string}
  - label: "People"
    name: "people"
    folder: "_data/people"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string", tagname: "h1"}
      - {label: "Job Title", name: "jobTitle", widget: "string", tagname: "h2"}
      - {label: "Image", name: "image", widget: "image", tagname: "img"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Role", name: "role", widget: "select", options: ["leadership", "developer"]}
