backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - label: "General Content"
    name: "generalContent"
    create: false
    delete: false
    files:
      - label: "Header"
        name: "siteHeader"
        file: "_data/header/header.yml"
        fields:
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Popout Tagline", name: "popoutTagline", widget: "string"}
          - {label: "Popout Text Block", name: "popoutTextBlock", widget: "markdown"}
      - label: "Footer"
        name: "siteFooter"
        file: "_data/footer/footer.yml"
        fields:
          - {label: "copyright", name: "copyright", widget: "string"}
          - {label: "address", name: "address", widget: "string"}
      - label: "What We Do"
        name: "whatWeDo"
        file: "_data/what-we-do/what-we-do.yml"
        fields:
          - {label: "Section Heading", name: sectionHeading, widget: string}
          - {label: "Tagline", name: whatWeDoTagline1, widget: string}
          - {label: "Tagline2", name: whatWeDoTagline2, widget: string}
          - {label: "Tagline3", name: whatWeDoTagline3, widget: string}
          - {label: "Text Block", name: whatWeDoTextBlock, widget: markdown}
      - label: "Get In Touch"
        name: "getInTouch"
        file: "_data/get-in-touch/get-in-touch.yml"
        fields:
          - {label: "Section Heading", name: sectionHeading, widget: string}
          - {label: "Tagline", name: "tagline", widget: string}
          - {label: "Button Text", name: "buttonText", widget: string}
          - {label: "Success Message", name: "successMessage", widget: string}
          - {label: "Beta Closed Message", name: "betaClosed", widget: string}
  - label: "People"
    name: "people"
    folder: "_data/people"
    format: "yaml"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string", tagname: "h1"}
      - {label: "Display Order", name: "displayOrder", widget: "number", required: false}
      - {label: "Job Title", name: "jobTitle", widget: "string", tagname: "h2"}
      - {label: "Role", name: "role", widget: "select", options: ["leadership", "developer"]}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Linked In", name: "linkedIn", widget: "string", required: false}
      - {label: "Github", name: "github", widget: "string", required: false}
